services:
  postgres:
    environment:
      POSTGRES_PASSWORD: mone_dev
    ports:
      - "5432:5432"

  nats:
    ports:
      - "4222:4222"
      - "8222:8222"

  api:
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      Jwt__Key: ThisIsADevelopmentKeyThatIsAtLeast32BytesLong!
    ports:
      - "8080:8080"
