// <auto-generated />
using System;
using Mone.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Mone.Infrastructure.Data.Migrations
{
    [DbContext(typeof(MoneDbContext))]
    [Migration("20260522160604_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Mone.Infrastructure.Data.Entities.CheckerAssignmentEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CheckerPluginId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("ConfigJson")
                        .HasColumnType("text");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean");

                    b.Property<Guid>("HostId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("HostId");

                    b.ToTable("checker_assignments", (string)null);
                });

            modelBuilder.Entity("Mone.Infrastructure.Data.Entities.HostEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("hosts", (string)null);
                });

            modelBuilder.Entity("Mone.Infrastructure.Data.Entities.HostTagEntity", b =>
                {
                    b.Property<Guid>("HostId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TagId")
                        .HasColumnType("uuid");

                    b.HasKey("HostId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("host_tags", (string)null);
                });

            modelBuilder.Entity("Mone.Infrastructure.Data.Entities.ProbeAssignmentEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BackoffOverrideJson")
                        .HasColumnType("text");

                    b.Property<string>("ConfigJson")
                        .HasColumnType("text");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean");

                    b.Property<Guid>("HostId")
                        .HasColumnType("uuid");

                    b.Property<string>("ProbePluginId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("ScheduleCron")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("HostId");

                    b.ToTable("probe_assignments", (string)null);
                });

            modelBuilder.Entity("Mone.Infrastructure.Data.Entities.ProbeResultEntity", b =>
                {
                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("TargetId")
                        .HasColumnType("uuid");

                    b.Property<string>("ProbeId")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<double>("DurationMs")
                        .HasColumnType("double precision");

                    b.Property<string>("MetadataJson")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.HasKey("Timestamp", "TargetId", "ProbeId");

                    b.ToTable("probe_results", (string)null);
                });

            modelBuilder.Entity("Mone.Infrastructure.Data.Entities.StatusHistoryEntity", b =>
                {
                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("TargetId")
                        .HasColumnType("uuid");

                    b.Property<string>("CheckerId")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("CurrentStatus")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("PreviousStatus")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Timestamp", "TargetId", "CheckerId");

                    b.ToTable("status_history", (string)null);
                });

            modelBuilder.Entity("Mone.Infrastructure.Data.Entities.TagEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("tags", (string)null);
                });

            modelBuilder.Entity("Mone.Infrastructure.Data.Entities.CheckerAssignmentEntity", b =>
                {
                    b.HasOne("Mone.Infrastructure.Data.Entities.HostEntity", "Host")
                        .WithMany("CheckerAssignments")
                        .HasForeignKey("HostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Host");
                });

            modelBuilder.Entity("Mone.Infrastructure.Data.Entities.HostTagEntity", b =>
                {
                    b.HasOne("Mone.Infrastructure.Data.Entities.HostEntity", "Host")
                        .WithMany("HostTags")
                        .HasForeignKey("HostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Mone.Infrastructure.Data.Entities.TagEntity", "Tag")
                        .WithMany("HostTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Host");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("Mone.Infrastructure.Data.Entities.ProbeAssignmentEntity", b =>
                {
                    b.HasOne("Mone.Infrastructure.Data.Entities.HostEntity", "Host")
                        .WithMany("ProbeAssignments")
                        .HasForeignKey("HostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Host");
                });

            modelBuilder.Entity("Mone.Infrastructure.Data.Entities.HostEntity", b =>
                {
                    b.Navigation("CheckerAssignments");

                    b.Navigation("HostTags");

                    b.Navigation("ProbeAssignments");
                });

            modelBuilder.Entity("Mone.Infrastructure.Data.Entities.TagEntity", b =>
                {
                    b.Navigation("HostTags");
                });
#pragma warning restore 612, 618
        }
    }
}
